### ISSUE TITLE
Papers

### ISSUE THREAD

**Issue by thejmazz** [bionode/gsoc16#10]
Not all are directly relevant, this has become somewhat of a reading list for myself. 
- [ ] Sequence Alignment/Map Format Specification
- [ ] The Sequence Alignment/Map format and SAMtools
- [ ] Trimmomatic- a flexible trimmer for Illumina sequence data
- [ ] The khmer software package- enabling efficient nucleotide sequence analysis
- [ ] Disk-based k-mer counting on a PC
- [ ] Teaser- Individualized benchmarking and optimization of read mapping results for NGS data
- [ ] KMC 2- Fast and resource-frugal k-mer counting
- [ ] **Snakemake—a scalable bioinformatics workflow engine**
- [x] **Nextflowposterver3**
- [ ] Rust-Bio- a fast and safe bioinformatics library
- [x] Differentially expressed genes associated with adaptation to different thermal environments in three sympatric Cuban Anolis lizards
- [ ] **NextflowWorkbench: Reproducible and Reusable Workflows for Beginners and Experts.**
- [ ] Comparison of normalization and differential expression analyses using RNA-Seq data from 726 individual Drosophila melanogaster
- [ ] A comprehensive evaluation of normalization methods for Illumina high-throughput RNA sequencing data analysis
- [ ] **near-optimal probabilistic rna-seq quantification** - [snakemake pipeline in repo](https://github.com/pachterlab/kallisto_paper_analysis/blob/nbt/Snakefile) - see [this](http://www.nextflow.io/blog/2016/best-practice-for-reproducibility.html) 
- [ ] BioDB extractor: customized data extraction system for commonly used bioinformatics databases
- [ ] Quantifying Reproducibility in Computational Biology: The Case of the Tuberculosis Drugome
- [ ] **The Lair: A resource for exploratory analysis of published RNA-Seq data**
- [ ] The gene cortex controls mimicry and crypsis in butterflies and moths

**Comment by bmpvieira** [comment]
Maybe this should be moved to bionode-watermill repo or closed if not relevant anymore.

**Comment by thejmazz** [comment]
this was mostly just my reading list for things related to gsoc project. ill close
